FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libffi-dev \
    libgl1-mesa-glx \
    python3-dev \
    pkg-config \
    curl \
    ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
