version: "3.9"

networks:
  network:
    external: true
    name: network

services:
  chat-frontend:
    image: sigirace/chat-frontend:latest
    container_name: chat-frontend
    ports:
      - "80:3000"
    networks:
      - network

  chat-backend:
    image: sigirace/chat-backend:latest
    container_name: chat-backend
    environment:
      - HAIQV_EMBED_NOMIC_URL=http://10.255.255.254:11434
      - HAIQV_URL=http://10.255.255.254:11434
    ports:
      - "8000:8000"
    networks:
      - network

  studio:
    image: sigirace/studio:latest
    container_name: studio
    environment:
      - HAIQV_EMBED_NOMIC_URL=http://10.255.255.254:11434
      - HAIQV_URL=http://10.255.255.254:11434
    ports:
      - "8001:8000"
    networks:
      - network

  rerank:
    image: sigirace/rerank:latest
    container_name: rerank
    ports:
      - "8002:8000"
    networks:
      - network
